export const countryNameToCode: Record<string, string> = {
  Italy: "IT",
  Germany: "DE",
  "United Kingdom": "GB",
  "UK": "GB",
  "United States": "US",
  "USA": "US",
  Monaco: "MC",
  Belgium: "BE",
  France: "FR",
  Spain: "ES",
  Canada: "CA",
  Brazil: "BR",
  Japan: "JP",
  Austria: "AT",
  Hungary: "HU",
  Australia: "AU",
  Netherlands: "NL",
  Mexico: "MX",
  "South Africa": "ZA",
  Bahrain: "BH",
  Argentina: "AR",
  Malaysia: "MY",
  Portugal: "PT",
  China: "CN",
  "United Arab Emirates": "AE",
  "UAE": "AE",
  Singapore: "SG",
  Turkey: "TR",
  Russia: "RU",
  Azerbaijan: "AZ",
  Sweden: "SE",
  Switzerland: "CH",
  "South Korea": "KR",
  "Saudi Arabia": "SA",
  India: "IN",
  Qatar: "QA",
  Morocco: "MA"
};
